package ru.ludwigandreas.notification.service;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.ludwigandreas.notification.settings.NotificationProperties;
import ru.ludwigandreas.notification.service.metrics.NotificationMetrics;
import ru.ludwigandreas.notification.repository.NotificationDeliveryRepository;
import ru.ludwigandreas.notification.repository.NotificationRequestRepository;
import ru.ludwigandreas.notification.repository.entity.CategoryKind;
import ru.ludwigandreas.notification.repository.entity.DeliveryPriority;
import ru.ludwigandreas.notification.repository.entity.NotificationDeliveryEntity;
import ru.ludwigandreas.notification.repository.entity.NotificationRequestEntity;
import ru.ludwigandreas.notification.repository.entity.NotificationSource;
import ru.ludwigandreas.notification.repository.entity.RequestStatus;
import ru.ludwigandreas.notification.service.exception.RequestNotFoundException;
import ru.ludwigandreas.notification.service.idempotency.IdempotencyStore;
import ru.ludwigandreas.notification.service.mapper.NotificationEntityMapper;
import ru.ludwigandreas.notification.service.model.NotificationCommand;
import ru.ludwigandreas.notification.service.model.NotificationRequestView;
import ru.ludwigandreas.notification.service.model.RenderRequest;
import ru.ludwigandreas.notification.service.model.RenderedPreview;
import ru.ludwigandreas.notification.service.queue.DeliveryFanOutService;
import ru.ludwigandreas.notification.service.template.RenderedTemplate;
import ru.ludwigandreas.notification.service.template.TemplateCoordinates;
import ru.ludwigandreas.notification.service.template.TemplateRenderer;
import ru.ludwigandreas.notification.service.template.TemplateModel;
import ru.ludwigandreas.notification.service.template.TemplateRevisionService;
import ru.ludwigandreas.security.principal.LudwigPrincipal;
import ru.ludwigandreas.security.principal.SecurityPrincipals;

/**
 * Transaction boundary of the ingress: one transaction writes the request, claims the idempotency
 * key and creates every delivery, or writes nothing.
 *
 * <h2>The duplicate path</h2>
 *
 * <p>The request row is inserted before the key is claimed, which looks backwards and is not. The
 * claim needs a request id to record, and the id is generated by the database - so the sequence is
 * insert, claim, and on a loss delete the row we just inserted and answer with the winner's. The
 * wasted insert happens only on the duplicate path, which is by definition the rare one, and nothing
 * is ever visible outside the transaction because the delete is inside it.
 *
 * <p>What makes this correct rather than merely plausible is that the claim statement blocks: a
 * second replica handling the same at-least-once record waits on the winner's row lock, and when it
 * proceeds it reads a committed request. So there is no window in which both see "no claim" - which
 * is the window a read-then-write implementation would have, and the reason this service does not
 * have one.
 */
@Slf4j
@Service
@Transactional
@RequiredArgsConstructor
public class NotificationServiceImpl implements NotificationService {

    private final NotificationRequestRepository requestRepository;
    private final NotificationDeliveryRepository deliveryRepository;
    private final DeliveryFanOutService fanOutService;
    private final IdempotencyStore idempotencyStore;
    private final TemplateRenderer templateRenderer;
    private final TemplateRevisionService templateRevisionService;
    private final NotificationEntityMapper mapper;
    private final NotificationProperties properties;
    private final NotificationMetrics metrics;
    private final ObjectMapper objectMapper;

    @Override
    public NotificationRequestView submit(NotificationCommand command) {
        NotificationRequestEntity request = requestRepository.saveAndFlush(newRequest(command));

        UUID owner = claim(command, request.getId());
        if (!owner.equals(request.getId())) {
            // Somebody else got here first. Drop the row we speculatively inserted and answer with
            // theirs, so a redelivery is indistinguishable from the original call.
            requestRepository.delete(request);
            metrics.recordRequestDuplicate(command.source().name());
            log.debug("Request with idempotency key {} is a duplicate of {}",
                    command.idempotencyKey(), owner);
            return view(existing(owner), true);
        }

        List<NotificationDeliveryEntity> deliveries = fanOutService.fanOut(request, command);
        if (deliveries.isEmpty()) {
            request.setStatus(RequestStatus.REJECTED);
            request.setRejectionReason("no recipient resolved to a usable address on any requested channel");
            metrics.recordRequestRejected(command.source().name());
        } else {
            request.setStatus(RequestStatus.FANNED_OUT);
            metrics.recordRequestAccepted(command.source().name());
        }

        log.info("Request {} ({}) fanned out into {} deliveries",
                request.getId(), command.templateKey(), deliveries.size());
        return mapper.toView(request, mapper.toViews(deliveries), false);
    }

    @Override
    @Transactional(readOnly = true)
    public RenderedPreview preview(RenderRequest request) {
        Locale locale = request.locale() == null
                ? Locale.forLanguageTag(properties.getPreferences().getDefaultLocale())
                : request.locale();
        TemplateCoordinates coordinates =
                new TemplateCoordinates(request.templateKey(), request.channel(), locale);

        RenderedTemplate rendered = templateRenderer.render(coordinates, previewModel(request, locale));
        // Recorded even though nothing is sent: a preview is the first time a freshly-edited
        // template is exercised, so this is where its revision naturally enters the trail.
        templateRevisionService.recordUsage(rendered.templateName(), rendered.templateVersion(),
                rendered.templateSource());
        return new RenderedPreview(
                request.templateKey(),
                request.channel(),
                rendered.resolvedLocale(),
                rendered.templateVersion(),
                rendered.subject(),
                rendered.htmlBody(),
                rendered.textBody());
    }

    /**
     * The preview's data model: the caller's variables plus a stand-in recipient context.
     *
     * <p>Without the recipient key, a preview of any template that greets somebody by name fails on a
     * missing variable while the real send succeeds - which makes the endpoint report problems that
     * do not exist, and an endpoint that cries wolf stops being used. Supplying the same shape the
     * fan-out builds is what makes "a preview that succeeds guarantees the send would" true rather
     * than aspirational.
     *
     * <p>A caller who passes their own {@code recipient} keeps it, so an author can check how a
     * particular name or a long display name renders.
     */
    private Map<String, Object> previewModel(RenderRequest request, Locale locale) {
        if (request.variables().containsKey(TemplateModel.RECIPIENT)) {
            return request.variables();
        }
        Map<String, Object> model = new LinkedHashMap<>(request.variables());
        model.put(TemplateModel.RECIPIENT, TemplateModel.sampleRecipient(
                locale.toLanguageTag(), properties.getPreferences().getDefaultTimezone()));
        return model;
    }

    /**
     * Claims the caller's key, or returns this request's own id when there is nothing to claim.
     *
     * <p>A command with no key is not an error: fire-and-forget callers who genuinely accept a
     * duplicate on a retry exist, and forcing a key on them would only produce keys made of random
     * values, which protect nothing while making the table grow.
     */
    private UUID claim(NotificationCommand command, UUID requestId) {
        if (!properties.getIdempotency().isEnabled()
                || command.idempotencyKey() == null
                || command.idempotencyKey().isBlank()) {
            return requestId;
        }
        String scope = command.source() == ru.ludwigandreas.notification.service.model.IngressSource.KAFKA
                ? properties.getIdempotency().getKafkaScope()
                : properties.getIdempotency().getRestScope();
        return idempotencyStore.claim(scope, command.idempotencyKey(), requestId);
    }

    private NotificationRequestEntity existing(UUID requestId) {
        return requestRepository.findById(requestId).orElseThrow(() -> new RequestNotFoundException(requestId));
    }

    private NotificationRequestView view(NotificationRequestEntity request, boolean duplicate) {
        return mapper.toView(request,
                mapper.toViews(deliveryRepository.findByRequestId(request.getId())), duplicate);
    }

    private NotificationRequestEntity newRequest(NotificationCommand command) {
        return NotificationRequestEntity.builder()
                .idempotencyKey(command.idempotencyKey())
                .source(NotificationSource.valueOf(command.source().name()))
                .templateKey(command.templateKey())
                .category(command.category())
                .categoryKind(CategoryKind.valueOf(command.categoryClass().name()))
                .priority(DeliveryPriority.valueOf(command.priority().name()))
                .variables(toJson(command.variables()))
                .requestedRecipients(toJson(command.recipients()))
                .status(RequestStatus.ACCEPTED)
                .scheduledAt(command.scheduledAt())
                .tenantId(tenantOfCaller())
                .correlationId(command.correlationId())
                .traceId(command.traceId())
                .build();
    }

    /**
     * The tenant the request belongs to, taken from the authenticated caller.
     *
     * <p>From the principal and never from the payload: a caller-supplied tenant id would let one
     * tenant file notifications under another's, and then read them back through the admin API,
     * because that column is exactly what the {@code TENANT} data scope matches on.
     *
     * <p>Empty for a background path with no principal - the Kafka consumer running without a
     * caller - in which case the deliveries inherit whatever the recipients' own profiles say.
     */
    private String tenantOfCaller() {
        return SecurityPrincipals.current()
                .flatMap(LudwigPrincipal::tenant)
                .orElse(null);
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JacksonException e) {
            // The variables came in as JSON and the recipients are this service's own records, so a
            // failure here means a caller sent something Jackson could read but not write back -
            // a self-referential structure, most likely. Rejecting is right; the alternative is a
            // request row with an unreadable payload that no operator can ever reproduce.
            throw new IllegalArgumentException("Request payload could not be serialized: "
                    + e.getOriginalMessage(), e);
        }
    }
}
