package ru.ludwigandreas.example.catalog.web.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import ru.ludwigandreas.example.catalog.service.model.Category;
import ru.ludwigandreas.example.catalog.service.model.NewProduct;
import ru.ludwigandreas.example.catalog.service.model.Product;
import ru.ludwigandreas.example.catalog.service.model.ProductUpdate;
import ru.ludwigandreas.example.catalog.web.dto.CategoryResponse;
import ru.ludwigandreas.example.catalog.web.dto.CreateProductRequest;
import ru.ludwigandreas.example.catalog.web.dto.ProductResponse;
import ru.ludwigandreas.example.catalog.web.dto.UpdateProductRequest;

/**
 * Boundary between the wire model and the service model, generated by MapStruct. The controller
 * therefore contains no conversion code at all - it validates, delegates, and maps.
 */
@Mapper
public interface ProductDtoMapper {

    @Mapping(target = "state", source = "status")
    NewProduct toCommand(CreateProductRequest request);

    @Mapping(target = "state", source = "status")
    @Mapping(target = "expectedVersion", source = "version")
    ProductUpdate toCommand(UpdateProductRequest request);

    @Mapping(target = "status", source = "state")
    ProductResponse toResponse(Product product);

    CategoryResponse toResponse(Category category);
}
