package ru.ludwigandreas.db.core.entity;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.domain.Persistable;

import java.io.Serializable;

/**
 * Base for entities whose id is generated by the database (defaults to a JPA 3.1 portable
 * {@code GenerationType.UUID}, i.e. use {@code ID = UUID} unless a different generated id type is needed).
 * <p>
 * This declares its own {@code id} field rather than extending {@link JpaBaseEntity}: JPA has no portable way
 * to add {@code @GeneratedValue} to an {@code @Id} field already declared (without generation) in a mapped
 * superclass, so the small amount of id/{@link Persistable} boilerplate is duplicated here instead.
 */
@Getter
@Setter
@MappedSuperclass
public abstract class GeneratedEntity<ID extends Serializable> extends AbstractEntity<ID> implements Persistable<ID> {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private ID id;

    @Override
    public boolean isNew() {
        return id == null;
    }
}
