package ru.ludwigandreas.db.core.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.domain.Persistable;

import java.io.Serializable;

/**
 * Base for entities whose id is assigned by the application or by an external system before persisting
 * (as opposed to {@link GeneratedEntity}, whose id is generated by the database). Because such an id is
 * already non-null before the first {@code save()}, {@link #isNew()} cannot rely on id-nullness and instead
 * tracks a transient flag flipped once the entity has actually been loaded from or persisted to the database.
 */
@Getter
@Setter
@MappedSuperclass
public abstract class JpaBaseEntity<ID extends Serializable> extends AbstractEntity<ID> implements Persistable<ID> {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private ID id;

    @Transient
    private boolean isNew = true;

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }
}
