package ru.ludwigandreas.notification.web.mapper;

import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import ru.ludwigandreas.notification.service.Pii;
import ru.ludwigandreas.notification.service.model.CategoryClass;
import ru.ludwigandreas.notification.service.model.ChannelType;
import ru.ludwigandreas.notification.service.model.DeliveryContentView;
import ru.ludwigandreas.notification.service.model.DeliveryTransition;
import ru.ludwigandreas.notification.service.model.DeliveryView;
import ru.ludwigandreas.notification.service.model.IngressSource;
import ru.ludwigandreas.notification.service.model.NotificationCommand;
import ru.ludwigandreas.notification.service.model.NotificationRequestView;
import ru.ludwigandreas.notification.service.model.PreferenceSetting;
import ru.ludwigandreas.notification.service.model.RecipientKind;
import ru.ludwigandreas.notification.service.model.RecipientProfileView;
import ru.ludwigandreas.notification.service.model.RecipientRef;
import ru.ludwigandreas.notification.service.model.RenderRequest;
import ru.ludwigandreas.notification.service.model.RenderedPreview;
import ru.ludwigandreas.notification.service.model.SuppressionView;
import ru.ludwigandreas.notification.web.dto.DeliveryContentResponse;
import ru.ludwigandreas.notification.web.dto.DeliveryResponse;
import ru.ludwigandreas.notification.web.dto.DeliveryTransitionResponse;
import ru.ludwigandreas.notification.web.dto.NotificationRequestResponse;
import ru.ludwigandreas.notification.web.dto.PreferenceResponse;
import ru.ludwigandreas.notification.web.dto.RecipientDto;
import ru.ludwigandreas.notification.web.dto.RecipientProfileResponse;
import ru.ludwigandreas.notification.web.dto.RenderPreviewRequest;
import ru.ludwigandreas.notification.web.dto.RenderPreviewResponse;
import ru.ludwigandreas.notification.web.dto.SendNotificationRequest;
import ru.ludwigandreas.notification.web.dto.SuppressionResponse;

/**
 * Boundary between the wire model and the service model, generated by MapStruct. The controllers
 * therefore contain no conversion code at all - they validate, delegate, and map.
 *
 * <h2>Masking happens here</h2>
 *
 * <p>Addresses are masked on the way out, in the one place every response passes through. Doing it in
 * each controller would work until somebody adds a controller; doing it in the service model would
 * mean the service could not read its own data. The boundary is the only place where "this value is
 * about to leave the process" is true by construction.
 *
 * <p>The exception is deliberate and narrow: {@link #toResponse(SuppressionView)} masks, and so does
 * the profile mapping, because both are read by support staff who need to confirm an address rather
 * than to use it. No endpoint returns a usable address to anybody.
 */
// imports = Pii.class makes the masker available to the expressions below by simple name in the
// GENERATED class, which is where they are compiled. Referencing it here rather than through a
// default method on this interface is deliberate: MapStruct adopts any unannotated String -> String
// method on a mapper as an implicit conversion and applies it to every String property it maps.
@Mapper(imports = Pii.class)
public interface NotificationDtoMapper {

    /**
     * The wire request, plus everything the adapter knows and the payload does not.
     *
     * <p>The idempotency key, the source and the correlation id come from the transport rather than
     * from the body - a caller could otherwise claim to be Kafka, or supply somebody else's
     * correlation id - so they are separate parameters rather than fields of the DTO.
     */
    @Mapping(target = "idempotencyKey", source = "idempotencyKey")
    @Mapping(target = "templateKey", source = "request.templateKey")
    @Mapping(target = "category", source = "request.category")
    @Mapping(target = "categoryClass", source = "request.categoryClass")
    @Mapping(target = "priority", source = "request.priority")
    @Mapping(target = "channels", source = "request.channels")
    @Mapping(target = "recipients", source = "request.recipients")
    @Mapping(target = "variables", source = "request.variables")
    @Mapping(target = "scheduledAt", source = "request.scheduledAt")
    @Mapping(target = "source", source = "source")
    @Mapping(target = "correlationId", source = "correlationId")
    @Mapping(target = "traceId", source = "traceId")
    NotificationCommand toCommand(SendNotificationRequest request, String idempotencyKey,
                                  IngressSource source, String correlationId, String traceId);

    /**
     * A recipient, resolved into its kind.
     *
     * <p>Hand-written because the kind is not a field on the wire - it is implied by which of the two
     * identifiers is present, which the DTO's own {@code @AssertTrue} has already guaranteed is
     * exactly one.
     */
    default RecipientRef toRef(RecipientDto dto) {
        if (dto == null) {
            return null;
        }
        boolean byUser = dto.userId() != null && !dto.userId().isBlank();
        return new RecipientRef(
                byUser ? RecipientKind.USER : RecipientKind.ADDRESS,
                byUser ? dto.userId() : null,
                byUser ? null : dto.address(),
                dto.locale() == null || dto.locale().isBlank() ? null : Locale.forLanguageTag(dto.locale()),
                dto.timezone(),
                dto.variables() == null ? Map.of() : dto.variables());
    }

    List<RecipientRef> toRefs(List<RecipientDto> recipients);

    // --- responses -------------------------------------------------------------------------------
    // Every toResponse overload sits together: the style rules require it, and it also means one
    // glance shows which service-layer models are published and which deliberately are not.

    @Mapping(target = "status", source = "state")
    @Mapping(target = "lastFailureClass", source = "lastFailureClass")
    DeliveryResponse toResponse(DeliveryView view);

    @Mapping(target = "state", source = "state")
    NotificationRequestResponse toResponse(NotificationRequestView view);

    DeliveryTransitionResponse toResponse(DeliveryTransition transition);

    DeliveryContentResponse toResponse(DeliveryContentView view);

    RenderPreviewResponse toResponse(RenderedPreview preview);

    PreferenceResponse toResponse(PreferenceSetting setting);

    /**
     * Addresses are masked: enough to recognise, not enough to use or to harvest.
     *
     * <p>Through {@code Pii.maskedOrNull} rather than a {@code default} method on this interface -
     * see the note on {@link #toLocale(String)} for why a {@code String -> String} helper here would
     * be applied to every String property in the mapper.
     */
    @Mapping(target = "emailAddress", expression = "java(Pii.maskedOrNull(view.emailAddress()))")
    @Mapping(target = "chatAddress", expression = "java(Pii.maskedOrNull(view.chatAddress()))")
    @Mapping(target = "webhookUrl", expression = "java(Pii.maskedOrNull(view.webhookUrl()))")
    RecipientProfileResponse toResponse(RecipientProfileView view);

    @Mapping(target = "address", expression = "java(Pii.maskedOrNull(view.address()))")
    SuppressionResponse toResponse(SuppressionView view);

    // --- collections and the remaining directions --------------------------------------------------

    List<DeliveryResponse> toDeliveryResponses(List<DeliveryView> views);

    List<DeliveryTransitionResponse> toTransitionResponses(List<DeliveryTransition> transitions);

    List<PreferenceResponse> toPreferenceResponses(List<PreferenceSetting> settings);

    List<SuppressionResponse> toSuppressionResponses(List<SuppressionView> views);

    @Mapping(target = "locale", source = "request.locale")
    RenderRequest toRenderRequest(RenderPreviewRequest request);

    /**
     * BCP 47 tag to {@link Locale}.
     *
     * <p>This one is deliberately left as an implicit conversion: {@code String -> Locale} is
     * unambiguous, there is exactly one such property in the whole mapper, and MapStruct has no
     * built-in conversion for it. Contrast the address masking above, which had to be moved out
     * precisely because {@code String -> String} is <em>not</em> unambiguous.
     */
    default Locale toLocale(String tag) {
        return tag == null || tag.isBlank() ? null : Locale.forLanguageTag(tag);
    }

    /** Enum twins, mapped by constant name; the build fails if the sets ever drift apart. */
    ChannelType toChannel(ru.ludwigandreas.notification.web.dto.ChannelTypeDto dto);

    ru.ludwigandreas.notification.web.dto.ChannelTypeDto toChannelDto(ChannelType channel);

    CategoryClass toCategoryClass(ru.ludwigandreas.notification.web.dto.CategoryClassDto dto);
}
