package ru.ludwigandreas.fileaction.format.xlsx.read;

import java.io.IOException;
import java.io.InputStream;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;

/**
 * The one thing about a workbook that has to be read before its cells can be understood: which date
 * epoch it uses.
 *
 * <h2>Why this is not optional</h2>
 *
 * <p>A date in a spreadsheet is a number of days since an epoch, and there are two epochs. Windows Excel
 * counts from 1899-12-30; Excel for Mac historically counted from 1904-01-01, and a workbook saved that
 * way carries {@code date1904="1"} in its {@code workbookPr}. A reader that assumes the first epoch reads
 * every date in such a file <strong>four years and one day early</strong>.
 *
 * <p>That failure is invisible in testing, because test fixtures are generated by the library doing the
 * reading, and it is invisible in review, because the code looks right. It shows up as an order dated 2022
 * in a file the user is looking at that says 2026 - and only if somebody notices.
 *
 * <p>POI's {@code XSSFReader} does not expose the flag, so it is read here with a StAX pull over
 * {@code xl/workbook.xml}. That document is small, is produced by the same tool that produced the sheets,
 * and is parsed with external entity resolution and DTD support off, which is the one thing that makes
 * parsing any XML from a user safe.
 */
final class WorkbookProperties {

    /** Whether the workbook counts dates from 1904-01-01 rather than 1899-12-30. */
    private final boolean date1904;

    private WorkbookProperties(boolean date1904) {
        this.date1904 = date1904;
    }

    /** Whether to use the 1904 date windowing when turning a serial number into a date. */
    boolean date1904() {
        return date1904;
    }

    /**
     * Reads the properties out of a workbook part.
     *
     * @param workbookData {@code xl/workbook.xml}, as {@code XSSFReader.getWorkbookData()} gives it
     * @return the properties; defaults to the Windows epoch, which is what a workbook with no
     *         {@code workbookPr} means
     * @throws IOException if the part cannot be read
     */
    static WorkbookProperties read(InputStream workbookData) throws IOException {
        XMLInputFactory factory = XMLInputFactory.newInstance();
        // An XLSX is a user-supplied file, so every XML part of it is untrusted input. Both of these are
        // off for the same reason: a DTD can declare an external entity, and an external entity is how a
        // spreadsheet reads a file off the server or opens a connection to one. POI sets these on its own
        // parsers; this one is ours, so it sets them itself rather than inheriting the habit.
        factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, Boolean.FALSE);
        factory.setProperty(XMLInputFactory.SUPPORT_DTD, Boolean.FALSE);
        XMLStreamReader reader = null;
        try {
            reader = factory.createXMLStreamReader(workbookData);
            while (reader.hasNext()) {
                if (reader.next() == XMLStreamConstants.START_ELEMENT
                        && "workbookPr".equals(reader.getLocalName())) {
                    String value = reader.getAttributeValue(null, "date1904");
                    return new WorkbookProperties(isTrue(value));
                }
            }
            return new WorkbookProperties(false);
        } catch (XMLStreamException malformed) {
            throw new IOException("xl/workbook.xml could not be parsed", malformed);
        } finally {
            closeQuietly(reader);
        }
    }

    /**
     * Whether an OOXML boolean attribute is true.
     *
     * <p>The schema allows {@code 1}, {@code true}, {@code 0} and {@code false}, and files in the wild
     * carry all four. Checking only for {@code "1"} reads a {@code date1904="true"} workbook with the wrong
     * epoch, which is the bug this whole class exists to prevent, arrived at by a different route.
     */
    private static boolean isTrue(String value) {
        return "1".equals(value) || "true".equalsIgnoreCase(value);
    }

    private static void closeQuietly(XMLStreamReader reader) {
        if (reader == null) {
            return;
        }
        try {
            reader.close();
        } catch (XMLStreamException ignored) {
            // Closing a reader over a part that is about to be closed itself has nothing to report, and
            // throwing from a finally block would replace the real failure with this one.
        }
    }
}
